name: Generate PDF from Markdown
on:
  push:
    branches:
      - main
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          journal: joss
          args: '-k ./paper.md'
      - name: Upload PDF to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-paper
          path: ./paper.pdf